        name: Deploy Hugo site to GitHub Pages

        on:
          push:
            branches:
              - main # or master

        jobs:
          deploy:
            runs-on: ubuntu-latest
            steps:
              - uses: actions/checkout@v4
                with:
                  submodules: true  # If you use themes as submodules
                  fetch-depth: 0    # Fetch all history for all branches and tags

              - name: Setup Hugo
                uses: peaceiris/actions-hugo@v2
                with:
                  hugo-version: 'latest' # or a specific version like '0.128.0'

              - name: Build Hugo site
                run: hugo --minify

              - name: Deploy to GitHub Pages
                uses: peaceiris/actions-gh-pages@v4
                with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./public
